
export default function Bt6() {
  return (
    <div>
        <h1>Bt6</h1>
            <p className="w-[500px] h-[200px] overflow-y-scroll text-clip overflow-hidden ">
            Lorem ipsum dolor sit amet consectetur, adipisicing elit. Doloribus natus adipisci ipsum necessitatibus modi eum dolores quisquam ratione ipsa sapiente voluptatibus, provident temporibus dignissimos a facilis. Quod, nisi? Obcaecati, vitae!
            Nemo incidunt sunt odit officia tempora! Minus quasi, suscipit nulla fugiat assumenda, incidunt sed doloremque qui et earum totam optio hic distinctio. Ratione itaque cupiditate eum illo iure minus delectus.
            Nobis molestiae quia omnis voluptates nostrum illum cumque atque provident, alias velit accusantium modi blanditiis quod voluptas officiis non exercitationem adipisci quo corporis rerum repudiandae. Deleniti ab non ipsum autem.
            Optio reiciendis quidem veniam quasi eveniet odio explicabo, quae natus recusandae maxime accusantium commodi asperiores nostrum neque nam porro ut provident quibusdam distinctio? Expedita nostrum ipsam numquam reprehenderit odit alias.
            Suscipit voluptatum dolorem laborum odit, qui exercitationem minima obcaecati, dolore sequi, non at blanditiis natus similique mollitia voluptate? Repellendus, reprehenderit deleniti excepturi omnis sed assumenda esse quidem ipsa eum doloribus?
            Architecto consequatur, optio laudantium debitis ullam deleniti culpa beatae ipsam voluptates dolorem ipsum voluptatum neque, perferendis fugit enim quibusdam harum nostrum eum. Commodi animi, laudantium possimus officia nobis eligendi harum?
            Voluptatum, odit vel? Corporis quod fugiat molestiae, modi et pariatur atque eaque consequatur nostrum quibusdam vero tempora libero repellat quam similique a commodi totam consectetur amet ducimus illo corrupti cumque.
            Nemo expedita dolor ab quis ex voluptatum dolores dolorum fugit culpa, vero repudiandae laboriosam impedit error illo mollitia odit quidem corporis quaerat iusto aut totam? Ipsum quaerat animi cum dolorem.
            Minus distinctio dignissimos, totam incidunt quaerat omnis deleniti labore minima nisi tempore quas, repellat aut aspernatur voluptatem asperiores eos ducimus nam dolorem harum sint impedit. Voluptatum provident necessitatibus quas rerum.
            At numquam harum delectus accusantium labore nostrum quasi temporibus atque repellendus quisquam dolores, veniam blanditiis debitis quos. Quasi, dolores distinctio, delectus hic facere quibusdam sequi, cupiditate quo tempore harum earum.
            Eveniet rerum assumenda hic delectus totam labore voluptatum iure, praesentium ad alias consequuntur fuga, cupiditate deserunt eius iusto? Voluptates illo esse dolor veniam ipsum minima mollitia optio velit, nisi alias!
            Saepe quae dolorem aperiam, odio deserunt est totam ullam porro ipsam magni eos enim ratione eaque deleniti natus, quibusdam voluptatem sapiente? Cupiditate sequi repudiandae, magnam nobis mollitia aut neque voluptas?
            Aspernatur dolorem optio nisi nemo perferendis sapiente voluptate architecto in, minima, officia iure atque! Dolores necessitatibus suscipit modi illo, repellat recusandae, doloribus culpa quidem distinctio voluptatibus, perspiciatis soluta error officiis?
            Nihil ipsa consectetur praesentium repellendus delectus eveniet, provident doloremque. Accusantium quos quia vitae quisquam et, error voluptate totam numquam pariatur, alias soluta dolorem facere facilis modi neque, repellendus molestiae enim.
            Laborum fugiat repudiandae explicabo quibusdam obcaecati voluptatibus voluptas, asperiores harum fuga maxime. Culpa error minus, veritatis dicta magnam amet ducimus quidem exercitationem minima suscipit optio id ullam blanditiis hic corrupti.
            Numquam deleniti laborum vel accusantium eligendi exercitationem quidem quo ipsum, voluptatum dolore ratione, magnam illo reprehenderit. Consectetur repellat fugiat ex enim placeat maiores quos modi molestias? Tenetur laboriosam optio beatae?
            Velit molestias eos labore quisquam iure nemo corporis reprehenderit ut deleniti commodi eum voluptate dolores tempora ipsa iusto itaque perspiciatis, quo adipisci placeat! Eligendi facere culpa reiciendis adipisci! Harum, animi.
            Optio modi molestias at exercitationem ad voluptatum tempora quisquam. Praesentium voluptatibus rem porro dolore dolorem molestias beatae? Quam cum fugiat aliquam aperiam delectus magnam, vel temporibus dolorum dignissimos eveniet tenetur?
            Fuga quam ipsa porro fugit placeat perspiciatis consequatur totam rerum! Voluptates natus laborum tempore exercitationem corporis commodi deleniti ratione illum odio, molestias voluptatem omnis expedita porro necessitatibus praesentium, assumenda itaque.
            Perferendis id, distinctio vero nisi nobis commodi sequi soluta ducimus blanditiis fuga quis excepturi expedita inventore mollitia natus? Ex nostrum sed ullam minima officiis qui atque, error fuga maiores eaque!
            At rem labore autem magni earum sit deserunt maiores, dolorum architecto quod possimus sint, beatae aperiam aut id repudiandae accusamus eligendi nulla, iste accusantium. Itaque at fuga error voluptatem omnis?
            Labore quo iusto impedit fuga omnis at ut accusantium. Est, consectetur provident necessitatibus iure odit temporibus similique, autem distinctio quas eligendi, libero possimus velit nostrum molestias iste ex eius explicabo.
            Voluptatem dolor nesciunt animi corrupti fugiat quas possimus ipsam accusantium quam amet officiis at velit, optio, earum pariatur exercitationem sed quia reiciendis, mollitia quae totam autem? Nisi quae iste hic?
            Cupiditate distinctio ea dignissimos aspernatur ut. Distinctio rerum, sit quas temporibus neque veniam totam optio aperiam repellat recusandae molestias quisquam, nemo minus error ducimus itaque ut, eveniet sint velit. Fugit?
            Ad ipsum officia nobis aspernatur qui eveniet quasi exercitationem ex quo perspiciatis tenetur voluptatum repellendus, ut cumque expedita perferendis, non inventore ipsam iure unde tempora veritatis beatae porro? Officia, excepturi.
            Ab eius veniam, nemo molestias laudantium quia incidunt consectetur repudiandae quisquam nobis similique vitae nostrum, modi sequi fuga sed repellat doloribus. Tenetur voluptate illum ullam quis consequatur voluptatibus inventore laudantium.
            Suscipit voluptates animi delectus aspernatur, nesciunt tempora magni ipsam provident eum beatae minima nobis amet voluptatibus rerum qui soluta est, ut eveniet, veniam dolores dicta. Sit voluptatibus nulla numquam vel?
            Nesciunt quidem placeat quia? Reprehenderit adipisci tenetur voluptatum esse obcaecati illum ipsam vero odit impedit, minima architecto, repellendus doloremque dolorum quae deserunt sint? Dolores, deserunt? At perspiciatis voluptas totam accusamus?
            Repellat soluta sapiente consequuntur voluptates fugit, consectetur eligendi obcaecati nemo ab? Molestiae quibusdam sint, deleniti sequi provident aliquid amet eius corrupti labore temporibus non neque nemo maiores. Sequi, voluptas dolore?
            Asperiores odit dolorum cum nobis similique saepe magnam quisquam dignissimos assumenda obcaecati harum eum ex praesentium esse ducimus nisi commodi, illum expedita id inventore enim architecto quaerat cumque a? Iure.
            Ab tempora temporibus amet laudantium error eveniet saepe sapiente et, ipsam perferendis aperiam fugiat iusto officia! Optio, quae nam! Vitae odio totam odit nemo iure ab reprehenderit, nam fuga magni?
            Labore nihil natus autem! Sunt at et quia incidunt omnis consequuntur soluta voluptatum voluptates beatae modi vel, tempore ipsum cumque ratione impedit aperiam rem suscipit magnam repudiandae blanditiis tempora! Optio.
            Enim praesentium tempora alias numquam veritatis nulla labore culpa aspernatur quibusdam. Distinctio ipsa rem ratione blanditiis, rerum dolores laboriosam obcaecati earum quod vero adipisci magnam fugit necessitatibus officiis porro voluptates.
            Doloremque, a nobis iste dolore omnis nam eos unde nulla fugit doloribus ex, quis esse excepturi modi corrupti incidunt ipsa molestias id? Explicabo voluptatibus, distinctio omnis sapiente accusamus incidunt tenetur.
            Asperiores aliquam, possimus sit dolorem laudantium ea delectus quisquam pariatur quaerat non eum consequuntur voluptate eligendi, architecto tempora rerum, expedita similique veniam quia! Quasi, aspernatur! Veritatis nemo molestias quisquam dignissimos?
            Libero reiciendis enim pariatur maxime. Quisquam illo aperiam asperiores vel placeat, impedit temporibus quos alias ea quia magnam consectetur nisi, quasi corrupti necessitatibus soluta dolore quibusdam saepe laborum excepturi esse.
            Ut fugit enim eveniet perferendis ipsam rerum facere, mollitia ad numquam, eaque amet veritatis illo et! Esse numquam, at asperiores voluptatibus alias ullam eligendi quasi minima deserunt temporibus reprehenderit quam.
            Quasi, officia dignissimos dolor dicta quos temporibus placeat quod distinctio veritatis voluptas dolores nesciunt eveniet vel exercitationem minus reiciendis pariatur ad earum facilis eaque autem consequuntur incidunt. Maiores, blanditiis beatae.
            Deserunt iusto, dolorem quod rerum quae dicta aspernatur eius exercitationem eum voluptates esse iure ullam harum officia voluptas recusandae cum facere quam id unde nostrum consectetur eligendi? Recusandae, laudantium ad.
            Quis, cumque quisquam veritatis sapiente aliquam cum, impedit iusto numquam distinctio dolorum odit ratione amet adipisci magnam officia error. Repudiandae officia deleniti explicabo qui, perspiciatis quo? Ad deleniti ratione in!
            Provident modi dolor ex nobis velit molestiae cumque? Soluta, dignissimos temporibus. Rerum est debitis esse corrupti, deserunt maiores officiis quisquam officia ipsa, quo praesentium nostrum, delectus excepturi mollitia quaerat. Eius.
            Sequi rem cum aut, eaque necessitatibus nobis fugiat assumenda enim placeat, molestiae sit voluptate consectetur maxime impedit, a sapiente incidunt illo corporis exercitationem dolore dolorum nisi ullam modi dolorem! Ad!
            Similique, nihil, vero voluptatem consequatur aspernatur dicta amet animi, facere veritatis quibusdam adipisci optio. Obcaecati, deleniti consectetur ducimus praesentium aperiam aliquid deserunt pariatur laboriosam iusto ut molestias, enim dolores aliquam!
            Sint quidem impedit tenetur cumque rem. Ad sunt quasi iusto sed, eum voluptatum necessitatibus laudantium tenetur cumque recusandae voluptate alias odit porro, pariatur odio, delectus beatae dolores commodi velit nulla?
            Eaque rem nesciunt velit corrupti commodi sed pariatur minus earum quisquam obcaecati nisi laudantium architecto error itaque, at, expedita sit. Nesciunt, beatae labore temporibus perferendis rerum quod nostrum ipsum nam?
            Laudantium commodi possimus, dolorem quasi tempora nostrum obcaecati culpa facilis molestias tenetur ipsum modi animi amet? Maiores tempora placeat, laboriosam esse dignissimos quasi suscipit quia nesciunt iste eveniet quos unde?
            Excepturi delectus reiciendis illo debitis, adipisci iste sunt asperiores nemo similique aut quas quo, dignissimos cumque animi autem totam magni tempore in eligendi, vitae qui? Alias beatae ad necessitatibus sint.
            Consequuntur, quas deserunt. Ut, architecto officia aut eligendi magni aperiam qui quod obcaecati harum sed unde! Amet tempora distinctio exercitationem modi consectetur autem, illum laboriosam assumenda pariatur praesentium provident reprehenderit!
            Quo repellat ducimus distinctio, tempora in quia neque, modi dolorem eos perferendis vero possimus quos deleniti corporis minima asperiores eius aut ratione. Iure explicabo magni quos, reiciendis numquam quod necessitatibus.
            Distinctio voluptates voluptatum sequi autem at nihil non impedit facilis, dolores facere tempore quos? Odit, praesentium cupiditate sunt quaerat voluptatum non tempore laboriosam accusamus libero, a sit nostrum unde vel?</p>
        </div>
  )
}
